config {
    type: "table",
    schema: "silver_clean_data",
    name: "chase_transactions",
    description: "Cleaned and standardized Chase credit card transaction data"
}

SELECT
  Transaction_Date AS transaction_date,
  Post_Date AS post_date,
  TRIM(Description) AS description,
  CASE
    WHEN Category IS NULL THEN 'Payment'
    ELSE TRIM(Category)
END
  AS raw_category,
  TRIM(Type) AS transaction_type,
  SAFE_CAST(Amount AS NUMERIC) AS amount,
  TRIM(Memo) AS memo,
  CURRENT_TIMESTAMP() AS processed_at
FROM
  ${ref("raw_chase_c_trans")}
WHERE
  Transaction_Date IS NOT NULL
QUALIFY
  ROW_NUMBER() OVER(PARTITION BY Transaction_Date, TRIM(Description),
    SAFE_CAST(Amount AS NUMERIC)
  ORDER BY
    Post_Date DESC ) = 1
